### ISSUE TITLE
Use of \n for newline

### ISSUE THREAD

**Issue by alimustafashah** [DDSNA/PYT3T#3]
In ProjectItself.py, there are many print(""), we can omit them and add "\n" in the printing statements. For example, 
```
48 print("")
49 print("Get to work!")
```
We can do
`print("\nGet to work!")`
Should I make the necessary changes?

**Comment by DDSNA** [comment]
Thank you kindly! :)
Please, feel free to edit.

**Comment by alimustafashah** [comment]
Can you assign the task to me?

**Comment by DDSNA** [comment]
Should be assigned now

**Comment by DDSNA** [comment]
Changes are appropriate and helped the project + provided insight to the OD.

**Comment by alimustafashah** [comment]
Thanks : )
